#!/usr/bin/env python
import sys, os, tarfile, subprocess, shlex
from lib import options
from lib.db import Db
from lib.kurt import *

MAX_PACKSIZE = 1024*1024*1024

GPG_COMMAND = "gpg -c --no-tty --passphrase PASSPHRASE --s2k-mode 3 --s2k-count 65011712 --batch --compress-algo none"

OPTSPEC = """
kurt [options] <path>
--
 Options:
o,output= path to the output directory
v,verbose increase log output (can be used more than once)
"""


def get_packs(path, known_files):
    singles = []

    packsize = 0
    paths = []
    for file_path, file_size in traverse_files(path):
        if file_path[len(path)+1:] in known_files:
            continue

        if packsize + file_size <= MAX_PACKSIZE:
            paths.append(file_path)
            packsize += file_size
        elif file_size > MAX_PACKSIZE:
            singles.append(([file_path], file_size))
        else:
            yield (paths, packsize)
            packsize = 0
            paths = []

            for single in singles:
                yield single
            singles = []
    if len(paths) > 0:
        yield (paths, packsize)


def main():
    o = options.Options(OPTSPEC)
    (opt, flags, extra) = o.parse(sys.argv[1:])

    if not extra:
        o.fatal('no path given')

    PATH = extra[0]
    if not os.path.exists(PATH):
        o.fatal('path <%s> does not exist' % PATH)

    if opt.output and not os.path.exists(opt.output):
        o.fatal('output-path <%s> does not exist' % opt.output)

    if opt.output:
        metapath = os.path.join(opt.output, 'meta')
    else:
        metapath = 'meta'
    if not os.path.exists(metapath):
        os.makedirs(metapath)

    db = Db(os.path.join(metapath, 'kurt.db'))

    known_files, maxpack = db.get_files()

    for index, pack in enumerate(get_packs(PATH, known_files)):
        packname = "pack%04d.tar.gz.gpg" % index
        if opt.output:
            packpath = os.path.join(opt.output, packname)
        else:
            packpath = packname
        f = open(packpath, 'wb')
        p = subprocess.Popen(shlex.split(GPG_COMMAND),
                             stdin=subprocess.PIPE,
                             stdout=f)
        t = tarfile.open(fileobj=p.stdin, mode='w:gz')

        paths, packsize = pack
        if opt.verbose:
            print "Pack %d (%dB)" % (maxpack+index+1, packsize)
        for path in paths:
            if opt.verbose:
                print "  %s" % path
            pathlen = len(PATH)
            try:
                tarinfo = t.gettarinfo(path)
                tarinfo.name = path[pathlen+1:]
                t.addfile(tarinfo, file(path))
                db.add(path[pathlen+1:], maxpack+index+1)
                file_stats = os.stat(path)
                file_size = file_stats.st_size
                db.add_meta(path[pathlen+1:], "size", file_size)
            except OSError:
                pass
            except IOError:
                pass

        t.close()
        p.stdin.flush()
        p.stdin.close()
        p.wait()
        f.close()
    db.commit()

if __name__ == "__main__":
    main()

